# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
    branches: [ vue ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  website:
    name: akshay2211
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: yarn build

      - name: Deploy site
        run: bash ./.github/workflows/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
